---
title: "Bio"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Following my graduation from the Master of Environmental Data Science program at UCSB’s Bren School in June, I’ve been working as a data analyst on the Ocean Health Index project at the National Center for Ecological Analysis and Synthesis (NCEAS). In this role, I’m analyzing quantitative and spatial data in order to generate this year’s OHI scores. Moving forward, I’m interested in using my data science skill set to support emerging projects in the environmental technology sector—particularly those geared towards climate change mitigation.

I’m originally from North Carolina, where I studied ecology at the University of North Carolina – Asheville among the southern Appalachian mountains. During this time I entered the realm of environmental research as an intern with the US Forest Service, conducting field work for several studies concerning eastern hemlock decline. Continuing along this path, I pursued undergraduate research looking at the habitat preferences of two orchid species, and spent another field season collecting and analyzing data for a forest regeneration study with NC State University. Wanting to try my hand at education and to get more involved in my community, I spent nearly three years as the Environmental Educator for a small nonprofit in Asheville. During this time I started teaching myself to code and was drawn to the idea of applying data science techniques to combat environmental issues. I discovered the MEDS program at the Bren School, and have been in Santa Barbara ever since.
