---
title: "Climbing"
description: "A little insight into my favorite pastime"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*"The beautiful thing to me about climbing is that you can’t justify it. It doesn’t pretend to be anything useful."*
\- **Royal Robbins**

<br>

## Places I've Climbed

Here's an interactive visualization I created of all the places I've climbed over the years. It includes location names, rock types, and the forms of climbing I've done at each spot.

```{r, code_folding=TRUE}
library(tidyverse)
library(sf)
library(leaflet)
library(here)

climbing <- read_csv(here("data", "climbing_locations.csv"))

climbing_sf <- climbing %>% 
  st_as_sf(coords = c("long", "lat"), crs = 4269)

climbing_sf %>% 
leaflet() %>%
addProviderTiles(providers$Esri.WorldImagery, group = "World Imagery") %>%
addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
addLayersControl(baseGroups = c("World Imagery", "Toner Lite")) %>%
addMarkers(label = climbing$name,
           popup = paste(climbing$climbing_type, "—", climbing$rock_type))
```



